version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    container_name: elasticsearch1
    environment:
      - node.name=elasticsearch
      - discovery.seed_hosts=elasticsearch
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.1
    container_name: kibana1
    environment:
      ELASTICSEARCH_URL: "http://IP:9200"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.9.1
    ports:
      - 8200:8200
    environment:
      - output.elasticsearch.hosts=['http://IP:9200']
      - apm-server.host="0.0.0.0:8200"
      - setup.kibana.host="IP:5601"
      - setup.template.enabled=true
      - logging.to_files=false
volumes:
  esdata1:
    driver: local
